title: Classifying Drivers' Actions using Convolutional Neural Networks
name: Classifying Drivers
description: Final project for MCSC 6230G
author: Alexandar Mihaylov and Luisa Rojas
theme: jekyll-theme-minimal